spring.application.name=FishingPal
fishingpal.target-species=perch

spring.datasource.url=jdbc:postgresql://localhost:5432/fishingpal
spring.datasource.username=postgres
spring.datasource.password=agents007
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=ZmlzaGluZ3BhbC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLWhtYWMtc2hhMjU2
jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

